version: '3'

services:
  s3-uploader-app:
    build:
      context: ./front-end/.
      args:
        VUE_APP_API_URL: http://localhost/api
    # Repository URI
    image: ${AWS_REPO_APP}
    # volumes:
    # - ./default.conf:/etc/nginx/conf.d/default.conf
    # environment:
    #   - VUE_APP_API_URL=http://localhost/apisha
    ports:
      - 80:80
  s3-uploader-api:
    build:
      context: ./back-end/.
    # Repository URI
    image: ${AWS_REPO_API}
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PORT=3000
    ports:
      - 3000:3000
    # restart: on-failure
  
