version: '3.2'

services:
  s3-uploader:
    build:
      context: ./
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
#   nginx:
#     image: nginx:latest
#     ports:
#       - "8080:8080"
#     volumes: 
#       - ./avid-frontend/build:/srv/www/static
#       - ./default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - avid-frontend
  